### PR TITLE
This is more or less how it should work for SSCS-3256

### PR DESCRIPTION
**Pull request by barbaracassani**
@bendiggle This is what I had in mind -- enabling the framework to accept ajax POSTs and leaving you to manage the redirects depending on outcome. You need a 200 to go in the success handler, and a 422 should comfortably send you to the error one.

### CODE REVIEW

**Comment by michaeldfallen** [comment]
@bendiggle can you describe the "2 pages pattern" you mention in the branch name? Not sure what problem this is attempting to solve.

**Comment by michaeldfallen** [comment]
Sorry, @barbaracassani can you describe the problem

**Comment by michaeldfallen** [comment]
Also 👋 Hi @barbaracassani thanks for contributing!! 🎉

**Comment by barbaracassani** [comment]
@michaeldfallen hi!! 👋 😄 
The idea is that the framework ought to be able to accept json payloads as well as form submissions. As we'll have a form that can submit also through ajax, a' la spa. 

The idea is that, if the user has javascript enabled, they should have an ajax-created and ajax-submitting form to add items, alongside a list of the already entered items, and after submission they shouldn't be redirected.

I don't know the framework very well yet, and it may be that there are other ways to achieve this, but after a quick chat with @bendiggle we saw this one as the least inconvenient. Happy to accept suggestions tho!

**Comment by michaeldfallen** [comment]
Ok, cool. Thanks for the context. 

Obviously I can't tell from this the why that informs what you're trying to do here so just to check, have you checked out the [AddAnother step type?](https://one-per-page.herokuapp.com/docs/steps/AddAnother)

It's designed to handle building a list of items up but does it using redirects. If that's your use case and you want to add Ajax to it I'd suggest you make the changes there. 

If the goal is to add Ajax to all form submission (which this would do as it's on Question) you should think about how a question would tell the browser if the answers were invalid (a simple 4xx without the errors isn't useful), and how the question would tell the browser which question to use next (otherwise you would be doubling your routing logic)

**Comment by barbaracassani** [comment]
@michaeldfallen thank you a lot for your support.

The story is now in @bendiggle 's hands but I'd like to be kept in the loop -- at the very least it will provide me an insight on the inner workings of the framework, that I still don't know very well.

**Comment by bendiggle** [comment]
Hi @barbaracassani @michaeldfallen Sorry I've only just seen these comments. We should be able to use the endpoints created by AddAnother with the ajax in order to post to the list (This is what we've done for our dates-cant-attend date-picker). But Michael brings up a good point about how we handle invalid answers. I haven't picked up this ticket yet so will have a proper look when I get the chance. 

P.S. You just can't keep away @michaeldfallen 😉

**Comment by barbaracassani** [comment]
Closing because made redundant by https://github.com/hmcts/one-per-page/pull/126

**Pull request closed without merging**
