### PR TITLE
Add another

### PR DESCRIPTION
**Pull request by michaeldfallen**
This PR adds a new step that allows you to collect a complex field multiple times without needing javascript.

To create an Add Another step you need to extend from `AddAnother` and provide a field you want to capture:

```
class DatesOfYourAppointments extends AddAnother {
  get field() {
    return date;
  }
}
```

and create a template that extends `look-and-feel/layouts/add_another.html` and has an `editItem` block which provides the input controls that will capture the given field:

```
% extends "look-and-feel/layouts/add_another.html" %}
{% from "look-and-feel/components/fields.njk" import date %}

{% set title %}
{{ "Tell us when you want your appointments" if isListMode }}
{{ "Enter a date for an appointment" if isEditMode }}
{% endset %}

{% block editItem %}
  <p>
    Don’t include weekends, bank holidays as the surgery will be closed.
  </p>
  {{ date(fields.item, "Date you can't attend") }}
{% endblock %}
```

(_note_: AddAnother provides the useful `isListMode` and `isEditMode` template locals that are handy when you want to change content depending on whether the user is viewing the list of items or adding/editing an item)

**Validating the list**

To validate the list of items you can implement the `validateList` function:
```
  validateList(list) {
    return list.check('Enter atleast 1 date', arr => arr.length > 0);
  }
```
AddAnother will pass you the list field we are using to parse and validate the items. You can attach any validations you need to it and return the result. In the example above we are adding a check to ensure the user enters at least 1 date.

**Validating the items during edit**

Any validations you apply to the field will be executed during editing or adding a field.

```
class DatesOfYourAppointments extends AddAnother {
  get field() {
    return date.check(
      errorFor('day', "We can't offer appointments at Christmas"),
      date => !(date.day === '25' && date.month === '12')
    );
  }
}
```

In the example above we are adding a validation that will be executed each time the user enters a date to warn them that we can't offer appointments at Christmas.

**Customise how an item is rendered in the list**

More complex field types will need custom rendering to make them easy for a user to read, an ISO timestamp isn't particularly user friendly for example.

You can customise how each item is rendered by providing an `item` block in your template:
```
{% block item %}
  {{ item.value.format('dddd, D MMMM YYYY') }}
{% endblock %}
```
In the example above we are rendering each item as "Sunday X January 20XX". The field representing the item currently being rendered is available inside that block as `item` and you can access the value it holds by calling `{{ item.value }}`.

_(Note: in the example above our item has already been parsed as a moment and so has the moment.js specific `.format` function on it)_

**Adding content to the list items layout**

You can add custom content to the list items layout by overriding the `listItems` block:
```
{% block listItems %}
  <p>
    Content to display above the list.
  </p>
  {{ super() }}
  <p>
    Content to display below the list.
  </p>
{% endblock %}
```
Be sure to call `{{ super() }}` inside the block or the list won't be rendered.

**Accessing the items in `values`, `answers`, `next`**

If you want to customise how the step presents it's answers or route to a different step based on the answers the user has given you can access the full list of items inside these functions via `this.fields.items`:
```
  answers() {
    return answer(this, {
      question: "Dates for your appointments",
      answer: this.fields.items.value.map(d => d.format('DD/MM/YYYY'))
    });
  }
```

### CODE REVIEW

**Comment by michaeldfallen** [comment]
Due to the drop in coverage I won't be merging this until the new year. 

SSCS need this now though so they can implement some steps before their deadline. I'll release this PR as a prerelease and continue working on tests before a full release in the new year.

**Comment by michaeldfallen** [comment]
This PR is now ready for merge and release. 

@endamccormack any chance you can review? 
@paulgain any chance you can feedback whether it has worked for you?

**Comment by bendiggle** [comment]
This a good solution to the issue we had on Submit your appeal. It seems to be working very well and was simple to implement.

**Comment by michaeldfallen** [comment]
Ok, reviewed, implemented by SSCS and now documented. Happy to merge this.

**Pull request merged**
